LmazonBookStore/Models/Basket.cs
using System;
using System.Collections.Generic;
using System.Linq;

namespace LmazonBookStore.Models
{
    public class Basket
    {
        public List<BasketLineItem> Items { get; set; } = new List<BasketLineItem>();

        public void AddItem (Books books, int qty)
        {
            BasketLineItem line = Items
                .Where(b => b.Books.BookId == books.BookId)
                .FirstOrDefault();

            if(line == null)
            {
                Items.Add(new BasketLineItem
                {
                    Books = books,
                    Quantity = qty
                });
            }
            else
            {
                line.Quantity += qty;
            }
        }

        public double CalcualteTotal()
        {
            double sum = Items.Sum(x => x.Quantity * x.Books.Price);

            return sum;
        }

        public int TotalBook()
        {
            int sum = Items.Sum(x => x.Quantity++);

            return sum;
        }

    }

    public class BasketLineItem
    {
        public int LineID { get; set; }

        public Books Books { get; set; }

        public int Quantity { get; set; }
    }

}

LmazonBookStore/Models/Books.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace LmazonBookStore.Models
{
    public partial class Books
    {
        [Key]
        [Required]
        public int BookId { get; set; }

        public string Title { get; set; }

        public string Author { get; set; }

        public string Publisher { get; set; }

        public string Isbn { get; set; }

        public string Classification { get; set; }

        public string Category { get; set; }

        public int PageCount { get; set; }

        public double Price { get; set; }
    }
}

LmazonBookStore/Models/BookstoreContext.cs
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace LmazonBookStore.Models
{
    public class BookstoreContext : DbContext
    {
        public BookstoreContext()
        {
        }

        public BookstoreContext(DbContextOptions<BookstoreContext> options)
            : base(options)
        {
        }

        public DbSet<Books> Books { get; set; }

    }
}

LmazonBookStore/Models/EFBookStoreRepository.cs
using System;
using System.Linq;

namespace LmazonBookStore.Models
{
    public class EFBookStoreRepository : IBookStoreRepository
    {
        private BookstoreContext context { get; set; }

        public EFBookStoreRepository (BookstoreContext temp)
        {
            context = temp;
        }

        public IQueryable<Books> Books => context.Books;
    }
}

LmazonBookStore/Models/IBookStoreRepository.cs
using System;
using System.Linq;

namespace LmazonBookStore.Models
{
    public interface IBookStoreRepository
    {
        IQueryable<Books> Books { get; }
    }
}

LmazonBookStore/Models/ViewModels/BooksViewModel.cs
using System;
using System.Linq;

namespace LmazonBookStore.Models.ViewModels
{
    public class BooksViewModel
    {
        public IQueryable<Books> Books { get; set; }

        public PageInfo PageInfo { get; set; }
    }
}

LmazonBookStore/Models/ViewModels/PageInfo.cs
using System;
namespace LmazonBookStore.Models.ViewModels
{
    public class PageInfo
    {
        public int TotalNumBooks { get; set; }

        public int BooksPerPage { get; set; }

        public int CurrentPage { get; set; }

        // Figure out how many pages we need
        // double means floating and cast into int 
        public int TotalPages => (int)Math.Ceiling((double)TotalNumBooks / BooksPerPage);
    }
}

LmazonBookStore/Components /TypesViewComponent.cs
using System;
using System.Linq;
using LmazonBookStore.Models;
using Microsoft.AspNetCore.Mvc;

namespace LmazonBookStore.Components
{
    public class TypesViewComponent : ViewComponent
    {
        private IBookStoreRepository repo { get; set; }

        public TypesViewComponent (IBookStoreRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {

            ViewBag.SelectedCategory = RouteData?.Values["category"];

            var types = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(types);
        }


    }
}

LmazonBookStore/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LmazonBookStore.Models;
using LmazonBookStore.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace LmazonBookStore.Controllers
{
    public class HomeController : Controller
    {
        private IBookStoreRepository repo;

        public HomeController (IBookStoreRepository temp)
        {
            repo = temp;
        }

        // GET: /<controller>/
        public IActionResult Index(string category, int pageNum = 1)
        {
            int pageSize = 10;

            var x = new BooksViewModel
            {
                Books = repo.Books
                .Where(b => b.Category == category || category == null)
                .OrderBy(b => b.Title)
                .Skip((pageNum - 1) * pageSize)
                .Take(pageSize),

                PageInfo = new PageInfo
                {
                    TotalNumBooks =
                        (category == null
                            ? repo.Books.Count()
                            : repo.Books.Where(x => x.Category == category).Count()),
                    BooksPerPage = pageSize,
                    CurrentPage = pageNum
                }
            };

            return View(x);
        }
    }
}

LmazonBookStore/Pages/ShoppingCart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LmazonBookStore.Infrastrusture;
using LmazonBookStore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LmazonBookStore.Pages
{
    public class ShoppingCartModel : PageModel
    {

        private IBookStoreRepository repo { get; set; }

        public ShoppingCartModel (IBookStoreRepository temp)
        {
            repo = temp;
        }

        public Basket basket { get; set; }

        public string ReturnUrl { get; set; }

        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
            basket = HttpContext.Session.GetJson<Basket>("basket") ?? new Basket();
        }

        public IActionResult OnPost(int bookId, string returnUrl)
        {
            Books b = repo.Books.FirstOrDefault(x => x.BookId == bookId);

            basket = HttpContext.Session.GetJson<Basket>("basket") ?? new Basket();

            basket.AddItem(b, 1);

            HttpContext.Session.SetJson("basket", basket);

            return RedirectToPage(new {ReturnUrl = returnUrl });

        }
    }
}

LmazonBookStore/Pages/ShoppingCart.cshtml
@page
@model LmazonBookStore.Pages.ShoppingCartModel
@{
}

<h2>Shopping Cart</h2>

<table class="table table-bordered table-striped">

    <thead>
        <tr>
            <th>Item</th>
            <th>Quantity</th>
            <th>Price</th>
            @*<th>Total Books</th>*@
            <th>Subtotal</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var i in Model.basket.Items)
        {
            <tr>
                <td class="text-left">@i.Books.Title</td>
                <td class="text-center">@i.Quantity</td>
                <td class="text-right">@i.Books.Price.ToString("$#,##0.00")</td>
                <td class="text-right">@((i.Quantity * i.Books.Price).ToString("$#,##0.00"))</td>
            </tr>
        }

    </tbody>

    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total: </td>
            <td class="text-right">
                @Model.basket.CalcualteTotal().ToString("$#,##0.00")
            </td>
        </tr>
    </tfoot>

    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total Book(s): </td>
            <td class="text-right">
                @Model.basket.TotalBook()
            </td>
        </tr>
    </tfoot>

</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
</div>

LmazonBookStore/Pages/_ShoppingCartLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>

    <div class="bg-dark text-white p-2">
        LMAZON 
    </div>

    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>

LmazonBookStore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "LMAZON";
}

@model BooksViewModel

<div class="text-center">
    @foreach (Books b in Model.Books)
    {
        <partial name="ProjectSummary" model="b"/>
    }
</div>


<div class="text-center">
    <div page-num="@Model.PageInfo" page-action="Index" page-classes-enabled="true"
         page-class="btn" page-class-normal="btn-outline-dark"
         page-class-selected="btn-primary" class="btn-group pull-right m-1">
    </div>
</div>

LmazonBookStore/Views/Shared/Components/Types/Default.cshtml
@{
}

@model IEnumerable<string>


<div class="d-grid gap-2">

    <a asp-controller="Home" asp-action="Index" asp-route-category="" asp-route-pageNum="1"
       class="btn btn-block btn-outline-secondary">Home</a>

    @foreach (string t in Model)
    {
        <a asp-controller="Home" asp-action="Index" asp-route-category="@t" asp-route-pageNum="1"
           class="btn btn-block @(t == ViewBag.SelectedCategory
           ? "btn-primary": "btn-outline-secondary")">@t</a>
    }

</div>

LmazonBookStore/Views/Shared/ProjectSummary.cshtml
@{
}

@model Books

<div class="card card-outline-primary m-1 p-1">

    <div class="bg-light p-1">
        <h4>@Model.Title</h4>

        <div class="bg-faded p-1">
            <h4>
                <span class="badge badge-pill badge-primary" style="float:right">
                    <small>USD$ @Model.Price</small>
                </span>
            </h4>
        </div>
    </div>

    <div class="card-text p-1">Author: @Model.Author</div>
    <div class="card-text p-1">Publisher: @Model.Publisher</div>
    <div class="card-text p-1">ISBN: @Model.Isbn</div>
    <div class="card-text p-1">Classification: @Model.Classification</div>
    <div class="card-text p-1">Category: @Model.Category</div>
    <div class="card-text p-1">Number of Page: @Model.PageCount pages</div>

    <form method="post" asp-page="/ShoppingCart">

        <input type="hidden" asp-for="@Model.BookId" />
        <input type="hidden" name="returnUrl"
               value="@ViewContext.HttpContext.Request.PathAndQuery()" />

        <span class="card-text">
            <button type="submit" class="btn btn-success btn-sm float-end">Add to Shopping Cart</button>
        </span>

    </form>

</div>

LmazonBookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="icon" href="https://media.geeksforgeeks.org/wp-content/cdn-uploads/gfg_200X200.png"
          type="image/x-icon">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <div class="bg-dark text-white p-2">
            <div class="container">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">LMAZON</a>
                @*<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                    </ul>
                </div>*@
            </div>
        </div>
    </header>

    <div class="row m-1 p-1">

        <div id="types" class="col-3">
            <vc:types></vc:types>
        </div>

        <div class="col-9">
            <div>
                @RenderBody()
            </div>
        </div>

    </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2022 - LMAZON BOOK STORE - <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            </div>
        </footer>
</body>
</html>